import:
  - display/desktop/xsetroot
  - display/color/solarized
  - display/client
  - display/tags
  - display/status/spacer
  - display/status/power
  - display/status/time
  - display/status/volume
  - control/mouse
  - control/keyboard/personal
  - control/keyboard/common/client
  - control/keyboard/personal/focus
  - control/keyboard/common/focus_by_number
  - control/keyboard/personal/launch
  - control/keyboard/personal/layout
  - control/keyboard/personal/move
  - control/keyboard/personal/menu

prefer:
  terminal: xterm
  browser:  opera
  editor:   vim
  filer:    thunar


display:
  font: "xft:DejaVuSans:pixelsize=13"
  bar: bottom
  column:
    mode: stack
    rule: |
      /mail/ -> 75+25
      /gimp/ -> 17+83+41
      /.*/ -> 50+50

  client:
    rule: |
      /^XMMS:/ floating=on
      /^xcalc:/ floating=on
      /^gimp:/ tags=gimp
      /^NX/ tags=netbook

  status:
    time: 
      '@format': '%a %d %b %I:%M'
      refresh: 30

#script:
#  after: focus_view "1:main"
